In [2]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [3]:
ds=pd.read_csv("product_data.csv")

In [30]:
print(ds.to_string())

     CustomerID     Product    Price  Quantity       City PurchaseDate
0          1052     Desktop  30000.0       4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0       3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0       2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0       1.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0       3.0     Mumbai   2022-04-11
5          1094      Laptop  60000.0       3.0     Mumbai   2022-03-12
6          1004      Laptop  30000.0       2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0       2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0       3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0       3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0       3.0  Bangalore   2021-08-14
11         1017     Desktop  45000.0       3.0       Pune   2022-08-09
12         1075     Desktop  30000.0       1.0       Pune   2021-09-28
13    

In [31]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   CustomerID    120 non-null    int64         
 1   Product       120 non-null    object        
 2   Price         120 non-null    float64       
 3   Quantity      120 non-null    float64       
 4   City          120 non-null    object        
 5   PurchaseDate  120 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.6+ KB


In [29]:
ds.drop_duplicates(inplace=True)


In [28]:
ds["CustomerID"].unique()

array([1052, 1041, 1057, 1038, 1013, 1094, 1004, 1034, 1086, 1092, 1074,
       1017, 1075, 1008, 1073, 1016, 1006, 1045, 1012, 1039, 1049, 1026,
       1065, 1028, 1036, 1037, 1082, 1007, 1064, 1085, 1070, 1088, 1044,
       1003, 1035, 1069, 1030, 1018, 1060, 1053, 1090, 1089, 1066, 1091,
       1019, 1071, 1000, 1002, 1076, 1061, 1062, 1024, 1055, 1032, 1005,
       1043, 1031, 1046, 1020, 1079, 1084, 1098, 1056, 1048, 1014, 1015,
       1011, 1095, 1023, 1027, 1059, 1040], dtype=int64)

In [25]:
ds["CustomerID"].duplicated().sum()

48

In [8]:
ds["Price"]=pd.to_numeric(ds["Price"],errors = 'coerce')

In [9]:
x=ds["Price"].median()
ds["Price"].fillna(x,inplace=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_10680\410612516.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Price"].fillna(x,inplace=True)


In [10]:
ds["Price"].unique()

array([30000., 45000., 60000., 15000.])

In [11]:
ds.info()


<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   CustomerID    120 non-null    int64  
 1   Product       120 non-null    object 
 2   Price         120 non-null    float64
 3   Quantity      96 non-null     object 
 4   City          120 non-null    object 
 5   PurchaseDate  120 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 6.6+ KB


In [12]:
ds["Quantity"]=pd.to_numeric(ds["Quantity"],errors = 'coerce')

In [13]:
ds["Quantity"].unique()

array([ 4.,  3.,  2.,  1., nan])

In [14]:
y=ds["Quantity"].median()
ds["Quantity"].fillna(y,inplace=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_10680\3970296594.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Quantity"].fillna(y,inplace=True)


In [15]:
ds["City"].unique()

array(['Bangalore', 'Delhi', 'Chennai', 'Mumbai', 'Pune'], dtype=object)

In [16]:
ds["PurchaseDate"]=pd.to_datetime(ds["PurchaseDate"],errors = 'coerce')

In [17]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120 entries, 0 to 119
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   CustomerID    120 non-null    int64         
 1   Product       120 non-null    object        
 2   Price         120 non-null    float64       
 3   Quantity      120 non-null    float64       
 4   City          120 non-null    object        
 5   PurchaseDate  120 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 6.6+ KB


In [18]:
print(ds.to_string())

     CustomerID     Product    Price  Quantity       City PurchaseDate
0          1052     Desktop  30000.0       4.0  Bangalore   2021-06-30
1          1041     Desktop  30000.0       3.0      Delhi   2023-01-21
2          1057  Smartphone  30000.0       2.0  Bangalore   2023-04-06
3          1038      Tablet  45000.0       1.0    Chennai   2023-07-05
4          1013  Smartphone  45000.0       3.0     Mumbai   2022-04-11
5          1094      Laptop  60000.0       3.0     Mumbai   2022-03-12
6          1004      Laptop  30000.0       2.0    Chennai   2022-02-25
7          1034      Laptop  30000.0       2.0    Chennai   2022-12-22
8          1086      Laptop  30000.0       3.0      Delhi   2022-10-23
9          1092     Desktop  30000.0       3.0     Mumbai   2022-03-12
10         1074      Laptop  45000.0       3.0  Bangalore   2021-08-14
11         1017     Desktop  45000.0       3.0       Pune   2022-08-09
12         1075     Desktop  30000.0       1.0       Pune   2021-09-28
13    

In [19]:
ds.to_csv("CleanedData2.csv")